
server:
    ssl:
        enabled: false

email:
    enabled: false
    template:
        server-link: http://localhost 
    SMTP-server: no-server.fr
    sender: unit-test@no-server.fr

spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: testUser
        password: password