

CREATE TABLE example (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	html varchar,
	html_id varchar,
	name varchar,
	CONSTRAINT example_pkey PRIMARY KEY (id)
);

CREATE INDEX example_html_id
ON example(html_id);