


CREATE TABLE registered_user (
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	email VARCHAR,
	hash_password VARCHAR,
	pseudo VARCHAR,
	verification_completed BOOLEAN,
	verification_link VARCHAR,

	CONSTRAINT registered_user_pkey PRIMARY KEY (id)
);

CREATE TABLE registered_token (
	id INT8 GENERATED BY DEFAULT AS IDENTITY,
	expiration_date TIMESTAMP,
	"token" VARCHAR,
	fk_user INT8,

	CONSTRAINT registered_token_pkey PRIMARY KEY (id),
	CONSTRAINT constraint_foreign_key_token_user FOREIGN KEY (fk_user) REFERENCES registered_user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_email
ON registered_user(email);

CREATE INDEX IF NOT EXISTS idx_user_pseudo
ON registered_user(pseudo);

CREATE INDEX IF NOT EXISTS idx_user_link
ON registered_user(verification_link);

CREATE INDEX IF NOT EXISTS idx_token_token
ON registered_token(token);

CREATE INDEX IF NOT EXISTS idx_visual_title
ON visual_novel(title);

CREATE INDEX IF NOT EXISTS idx_visual_release_date
ON visual_novel(release_date);

CREATE INDEX IF NOT EXISTS idx_rel_visual_tag_tagName
ON rel_visual_tag(fk_tag);