


CREATE TABLE registered_user (
	id INT4 GENERATED BY DEFAULT AS IDENTITY,
	email VARCHAR,
	hash_password VARCHAR,
	pseudo VARCHAR,
	verification_completed BOOLEAN,
	verification_link VARCHAR,

	CONSTRAINT registered_user_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_user_email
ON registered_user(email);

CREATE INDEX IF NOT EXISTS idx_user_pseudo
ON registered_user(pseudo);

CREATE INDEX IF NOT EXISTS idx_user_link
ON registered_user(verification_link);