name: Tests unitaires

on:
  push:
    branches: ["main", "feature/draft"]
  pull_request:
    branches: [ "main"]

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Build application
      run: mvn package -DskipTests
    - name: Unit Test
      run: mvn verify